server:
  port: 9000

spring:
  application:
    name: initialization-zuul

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/

#zuul:
#  prefix: /imooc
#  routes:
#    course:
#      path: /homepage-course/**
#      serviceId: eureka-client-homepage-course
#      strip-prefix: false
#    user:
#      path: /homepage-user/**
#      serviceId: eureka-client-homepage-user
#      strip-prefix: false
